In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("/content/drive/MyDrive/Resume Classification/Raw_Resume.csv")

In [4]:
df

Category                                        Raw_Details
0     Data Engineer  Data Engineer, Jayesh Jain\n\n\n\n400104 Mumba...
1     Data Engineer  ABOUT ME\n\nI’m a data scientist with great in...
2     Data Engineer  Vincent Le Goualher \n1426 Concise, CH \nBorn ...
3     Data Engineer  Sudarshan Babu | CV \n\tsudarshan@ttic.edu –We...
4     Data Engineer  Tamilnadu, India. JUNIOR DATA ENGINEER\t\n\n\n...
5    Data Scientist  GOKULA VARSHINI M\n\nDATA SCIENTIST\n\nAbout M...
6    Data Scientist  @datasciencenik@gmail.com \n\nNikunj Maheshwar...
7    Data Scientist  Ashish Patel \n\nSr. Data Scientist & Author \...
8    Data Scientist  Work Experience\n\n\n\n\n\n\t2020–current Soli...
9    Data Scientist  Jared Sylvester, Ph.D.\n\nCurriculum Vitæ\n\n4...
10  Design Engineer  CURRICULUM VITAE\n\nMr. SACHIN JALDE\n\nGmail ...
11  Design Engineer  SAHIL SHARMA \n\n\n\nMobile : +91-9988291420 \...
12  Design Engineer  Curriculum Vitae Ujjwal Kumar \nCurrent Addres...
13  Design Engineer  M I C H A E L  G A L V I N \n115 Stanworth Lan...
14   Java Developer  SOPHIE TAN \nFlat 404 Baldwin Point, 6 Sayer S...
15   Java Developer  Emarson Que \nTo be part of an organization wh...
16   Java Developer  Elena Samsonova Java developer \nKyiv, Ukraine...
17   Java Developer  Artem Nabirkin \nSr. Software Development Engi...
18   Java Developer  Justine Leleu\n\nLicense\n\nAddress\n\n\n\nB +...

In [5]:
df.dtypes

Category       object
Raw_Details    object
dtype: object

In [6]:
df.isna().sum()

Category       0
Raw_Details    0
dtype: int64

In [7]:
df.shape

(19, 2)

In [9]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
df['category'] = encoder.fit_transform(df['Category'])

In [10]:
df.columns

Index(['Category', 'Raw_Details', 'category'], dtype='object')

In [23]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
x = vectorizer.fit_transform(df['Raw_Details'])
y = df["category"]

In [24]:
x

<19x3356 sparse matrix of type '<class 'numpy.int64'>'
	with 6163 stored elements in Compressed Sparse Row format>

In [25]:
y

0     0
1     0
2     0
3     0
4     0
5     1
6     1
7     1
8     1
9     1
10    2
11    2
12    2
13    2
14    3
15    3
16    3
17    3
18    3
Name: category, dtype: int64

In [26]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score


In [27]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [28]:
model = LogisticRegression()

In [29]:
model.fit(x_train, y_train)

LogisticRegression()

In [31]:
y_pred = model.predict(x_test)

In [32]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.75


In [41]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score, roc_curve, auc


# Calculate confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)

# Calculate precision
precision = precision_score(y_test, y_pred, average='macro')
print("Precision:", precision)

# Calculate recall
recall = recall_score(y_test, y_pred, average='macro')
print("Recall:", recall)

# Calculate F1 score
f1 = f1_score(y_test, y_pred, average='macro')
print("F1 Score:", f1)


Confusion Matrix:
[[2 0 0]
 [1 0 0]
 [0 0 1]]
Precision: 0.5555555555555555
Recall: 0.6666666666666666
F1 Score: 0.6


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [60]:
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

# Define the parameter grid
param_grid = {
    'criterion': ['gini', 'entropy'],
    'max_depth': [50],
    'min_samples_split': [2],
    'min_samples_leaf': [1]
}

# Initialize the decision tree classifier
dt_classifier = DecisionTreeClassifier()

# Initialize GridSearchCV
grid_search = GridSearchCV(dt_classifier, param_grid, cv=5, scoring='accuracy')

# Fit the GridSearchCV object to the training data
grid_search.fit(X_train, y_train)

# Get the best parameters and the best score
best_params = grid_search.best_params_
best_score = grid_search.best_score_

print("Best Parameters:", best_params)
print("Best Score:", best_score)

# Use the best model from GridSearchCV to make predictions
best_model = grid_search.best_estimator_
y_pred = best_model.predict(X_test)

# Evaluate the accuracy of the best model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)


Best Parameters: {'criterion': 'gini', 'max_depth': 50, 'min_samples_leaf': 1, 'min_samples_split': 2}
Best Score: 0.6666666666666666
Accuracy: 0.75


/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  warnings.warn(


In [66]:
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

# Define the parameter grid for grid search
param_grid = {'C': [0.1, 1, 10, 50],
              'gamma': ['scale', 'auto', 0.1, 0.01, 0.001]}

# Initialize the SVM model
svm_model = SVC(kernel='rbf')

# Initialize GridSearchCV
grid_search = GridSearchCV(svm_model, param_grid, cv=5, scoring='accuracy')

# Fit the grid search to the data
grid_search.fit(X_train, y_train)

# Get the best parameters
best_params = grid_search.best_params_
print("Best Parameters:", best_params)

# Get the best model
best_model = grid_search.best_estimator_

# Make predictions on the testing data
y_pred = best_model.predict(X_test)

# Evaluate the model's performance
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)



/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  warnings.warn(


Best Parameters: {'C': 10, 'gamma': 0.1}
Accuracy: 0.5


In [68]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Generate synthetic data for demonstration
x, y = make_classification(n_samples=1000, n_features=20, n_classes=2, random_state=42)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

# Initialize a base classifier (decision tree in this example)
base_classifier = DecisionTreeClassifier(max_depth=1)

# Initialize the Random AdaBoost model
random_adaboost_model = AdaBoostClassifier(base_classifier, n_estimators=50, random_state=42)

# Train the model on the training data
random_adaboost_model.fit(X_train, y_train)

# Make predictions on the testing data
y_pred = random_adaboost_model.predict(X_test)

# Evaluate the accuracy of the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)


Accuracy: 0.87


In [69]:
import numpy as np
import pandas as pd
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

# Convert the data into DMatrix format for XGBoost
dtrain = xgb.DMatrix(X_train, label=y_train)
dtest = xgb.DMatrix(X_test, label=y_test)

# Set the parameters for the XGBoost model
params = {
    'max_depth': 3,  # maximum depth of a tree
    'learning_rate': 0.1,  # step size shrinkage used to prevent overfitting
    'objective': 'binary:logistic',  # objective function (logistic regression for binary classification)
    'eval_metric': 'logloss'  # evaluation metric (logarithmic loss)
}

# Train the XGBoost model
num_rounds = 100  # number of boosting rounds
model = xgb.train(params, dtrain, num_rounds)

# Make predictions on the testing data
y_pred_proba = model.predict(dtest)
y_pred = np.round(y_pred_proba)  # convert probabilities to binary predictions

# Evaluate the accuracy of the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)


Accuracy: 0.895


In [70]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Generate synthetic data for demonstration
x, y = make_classification(n_samples=1000, n_features=20, n_classes=2, random_state=42)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

# Initialize the KNN model
k = 5  # number of neighbors
model = KNeighborsClassifier(n_neighbors=k)

# Train the model on the training data
model.fit(X_train, y_train)

# Make predictions on the testing data
y_pred = model.predict(X_test)

# Evaluate the accuracy of the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)


Accuracy: 0.81


In [71]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Generate synthetic data for demonstration
x_train, y = make_classification(n_samples=1000, n_features=20, n_classes=2, random_state=42)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

# Initialize the Gradient Boosting Classifier
gbm = GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, max_depth=3, random_state=42)

# Train the GBM model
gbm.fit(X_train, y_train)

# Make predictions on the testing data
y_pred = gbm.predict(X_test)

# Evaluate the accuracy of the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)


Accuracy: 0.91
